# Site settings
#name: Alessandra Bilardi
description: "All can reduced to an equation or a pattern."
url: "https://alessandra.bilardi.net"
title: "alessandra.bilardi.net"

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  bilardi
#codepen_username: your_codepen_username_goes_here
#facebook_username: your_facebook_username_goes_here
#vk_username: your_vk_username_goes_here
twitter_username: abilardi
#google_plus_username: your_google_plus_username_goes_here
#linkedin_username: bilardi
#vine_username:  your_vine_username_goes_here
#instagram_username:  your_instagram_username_goes_here
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: 1472538
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#wikipedia_username: Bilardi
resume_url: "/resume"
bookmark_url: "/bookmarks"
#lastfm_username: your_lastfm_username_goes_here
blog_url: "/notes"
#email: your-email@example.domain
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"
avatar_img_path: "https://s3-eu-west-1.amazonaws.com/cdn.bilardi.net/alessandra/index/glider.3d.png"


front_img: yes
#front_img_path: "imgs/background.jpg"
front_img_path: "https://s3-eu-west-1.amazonaws.com/cdn.bilardi.net/alessandra/index/background.jpg"


favicon_img: yes
#favicon_img_path: "imgs/favicon.ico"
favicon_img_path: "https://s3-eu-west-1.amazonaws.com/cdn.bilardi.net/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty

# Tracking
googleAnalitycsID: UA-151979312-1
